spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/propertydb
    driver-class-name: org.postgresql.Driver
    username: property_user
    password: 3772

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

naver:
  maps:
    js-key-id: 2ihhwpahs3
  geocoding:
    key-id: 2ihhwpahs3
    key: c7FRp9eB5zXLlO7yYP9zNKPXorjqOf9L08DSwHZ4

app:
  upload-dir: ./data/uploads

logging:
  file:
    name: ./data/logs/app.log